name: Déploiement Automatisé

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Début du déploiement
        run: echo "Début du déploiement"

      - name: Afficher le secret (masqué)
        run: |
          echo "Le token de déploiement est : ${{ secrets.DEPLOY_TOKEN }}"

      - name: Déploiement terminé
        run: echo "Déploiement terminé par [Abdoul Fattahi]"